include: package:pedantic/analysis_options.yaml

analyzer:
  # Lint rules and documentation, see http://dart-lang.github.io/linter/lints
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
